name: Digestabot with GPG Signature

on:
  workflow_dispatch:

jobs:
  image-update:
    name: Digestabot with GPG Signature
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/digestabot@v1.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        create-pr: true
        title-for-pr: "Update Chainguard images to latest versions"
        use-gitsign: true 
        branch-for-pr: test_cg 
        signoff: true 
        author: sschubertchainguard <scott.schubert@chainguard.dev>

    - name: Import GPG key
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo "trusted-key $GPG_KEY_ID" >> ~/.gnupg/gpg.conf
        git config --global user.signingkey "$GPG_KEY_ID"
        git config --global commit.gpgsign true
        git config --global user.name "sschubertchainguard"
        git config --global user.email "scott.schubert@chainguard.dev"
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    - name: Make signed commit
      run: |
        git checkout test_cg
        echo "Follow-up signed commit from CI" >> followup.txt
        git add followup.txt
        git commit -m "Follow-up signed commit"
        git push origin test_cg
