name: Digestabot - test

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"



jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/digestabot@v1.2.2
      with:

        token: $(( secrets. GITHUB_TOKEN ))
        create-pr: true
        title-for-pr: "Update Chainguard images to latest versions"
        use-gitsign: true 
        branch-for-pr: test_cg 
        signoff: true
        author: sschubertchainguard <scott.schubert@chainguard.dev›
