name: Digestabot - GPG

on:
  workflow_dispatch:

jobs:
  image-update:
    name: Digestabot Update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/digestabot@v1.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        create-pr: false
        branch-for-pr: test_cg 
        signoff: false
        author: sschubertchainguard <scott.schubert@chainguard.dev>

    - uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Update images digest
        branch: test_cg 
        signoff: false
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        sign-commits: true
        delete-branch: true
