name: GPG Signed PR

on:
  workflow_dispatch:

jobs:
  gpg-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Import GPG key
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo "trusted-key $GPG_KEY_ID" >> ~/.gnupg/gpg.conf
        git config --global user.signingkey "$GPG_KEY_ID"
        git config --global commit.gpgsign true
        git config --global user.name "sschubertchainguard"
        git config --global user.email "scott.schubert@chainguard.dev"
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    - name: Create branch and commit
      run: |
        branch_name=gpg-signed-test
        git checkout -b "$branch_name"
        echo "test $(date)" >> test.txt
        git add test.txt
        git commit -m "Add GPG-signed update"
        git push origin "$branch_name"
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    - name: Open or update PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add GPG-signed update"
        branch: gpg-signed-test
        title: "Test GPG-signed commit"
        body: |
          This PR includes a GPG-signed commit.
        signoff: false  # GPG signature already applied by `git commit`
